### ISSUE TITLE
NPM add error

### ISSUE THREAD

**Issue by bryanrscott** [janosgyerik/upvotejs#13]
When adding with yarn to a project an error is generated.

yarn add https://github.com/janosgyerik/jquery-upvote
yarn add v0.20.3
[1/4] Resolving packages...
error Couldn't find manifest in "https://github.com/janosgyerik/jquery-upvote".

Looks like package.json is missing, possible suggestion below

**Comment by bryanrscott** [comment]
`{
  "name": "jquery-upvote",
  "title": "Jquery Upvote",
  "version": "1.0.2",
  "description": "A jquery voting plugin",
  "dependencies": {
    "jquery": ">=3.0"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/janosgyerik/jquery-upvote"
  },
  "keywords": [
    "jquery",
    "upvote"
  ],
  "main": "./lib/jquery.upvote.js",
  "style":"./lib/jquery.upvote.css",
  "files": [
    "lib"
  ],
  "homepage": "https://janosgyerik.github.io/jquery-upvote",
  "author": {
    "name": "Janos Gyerik",
    "url": "https://twitter.com/janosgyerik"
  },
  "contributors": [
    {
      "name": "HappyZombies",
      "url": "https://github.com/HappyZombies"
    },    
    {
      "name": "Tomas Liubinas",
      "url": "https://github.com/tomasliubinas"
    },   
    {
      "name": "dilip-vishwa",
      "url": "https://github.com/dilip-vishwa"
    }
  ]
}`

**Comment by janosgyerik** [comment]
Thanks for the heads up, added it.
