### ISSUE TITLE
svg image not showing in chrome 72

### ISSUE THREAD

**Issue by MoshEdmodo** [janosgyerik/upvotejs#16]
Installed the package, but the svg image clickable but blank in chrome 72 on win7.

**Comment by janosgyerik** [comment]
What do you mean clickable? When you click the count value changes?

Can you please include a screenshot?

**Comment by MoshEdmodo** [comment]
Chrome message: (index):1 Refused to apply style from 'http://localhost:3001/static/dist/upvotejs/upvotejs.js' because its MIME type ('text/plain') is not a supported stylesheet MIME type, and strict MIME checking is enabled. 
![image](https://user-images.githubusercontent.com/40410381/54063923-c2da6980-41c4-11e9-89ad-bc6b3d1b956a.png)

**Comment by janosgyerik** [comment]
From the error message it seems that `upvotejs.js` is included as a stylesheet, as if you're trying to include it with a `<link>` element instead of a `<script>`.

Btw there is no file named `upvotejs.js` in the package. It would be too difficult for me to help you debug a modified version. I suggest to first try to make it work with an unmodified version.

**Comment by MoshEdmodo** [comment]
that was a typo in my report, original bug is chrome is not displaying svg file, http://localhost:3001/static/dist/upvotejs/upvotejs.svg?v=1   <link rel="stylesheet" href="/static/dist/upvotejs/upvotejs.css">
    <script src="/static/dist/upvotejs/upvotejs.vanilla.js"> </script>
    <script>$( document ).ready(function() { Upvote.create('theid'); } ); </script>  
<div id="theid" class="upvotejs">
    <a class="upvote"></a> <span class="count">0</span> <a class="downvote"></a> <a class="star"></a> </div>   
![image](https://user-images.githubusercontent.com/40410381/54075249-fc0ceb00-4251-11e9-8ccb-dace1156ab7c.png)

**Comment by janosgyerik** [comment]
@MoshEdmodo Is this still an issue? How do you run the webserver that serves the files at your `localhost:3001` ?

**Comment by MoshEdmodo** [comment]
It is a golang webserver.  From google search, I gathered it was a chrome issue with some svg files not rendering. So I switched to a simpler rating api https://github.com/auxiliary/rater

**Comment by janosgyerik** [comment]
Thanks for the update @MoshEdmodo. I think it's an issue with the golang webserver you're using, and not with Chrome, or the svg. As you mentioned earlier, the MIME type of the stylesheet is not supported. The MIME type is something the webserver provides. And I don't think a modern browser such as Chrome has basic issues rendering svgs.
