### ISSUE TITLE
Add action type parameter in the callback

### ISSUE THREAD

**Issue by arieswandari** [janosgyerik/upvotejs#8]
Is there any way I can get action type in callback function, since its only param dt there. I know that current done action marked as true and false for upvoted, downvoted, checked, or starred. But if user click e.g. upvoted and checked in one session, then there will be two items with value true/false, which I cant decide which one executed.

**Comment by janosgyerik** [comment]
Will it help if I add the possibility of two kinds of callback methods: one for upvote/downvote, and one for star/unstar? This will make sense, because these are really quite unrelated actions, with likely different api endpoints.

**Comment by arieswandari** [comment]
Yes, that make sense. Need to create upvote/cancel-upvote, downvote/cancel-downvote, star/unstar. Cant it make as a parameter in same callback? Currently I modified your code, add 4th button.check/uncheck.

**Comment by janosgyerik** [comment]
Better late than never. I added an `action` field to the payload. At the same time I moved the `count`, `upvoted`, `downvoted`, `starred` fields inside a new field named `newState`. (This is an API breaking change, but I think it was worth it.)

See the updated README for more details.
